-- 1. Create the notifications_queue table
CREATE TABLE IF NOT EXISTS public.notifications_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    processed_at TIMESTAMPTZ,
    status TEXT DEFAULT 'pending' NOT NULL, -- pending, processing, sent, failed
    retry_attempts INT DEFAULT 0 NOT NULL,
    last_error TEXT,
    
    -- Notification details
    template_id TEXT NOT NULL,
    recipient_user_id UUID, -- Can be null for admin emails
    recipient_email TEXT,   -- Can be null if we need to look it up via user_id
    notification_params JSONB
);

-- 2. Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_notifications_queue_status ON public.notifications_queue(status, created_at);

-- 3. Add comments for clarity
COMMENT ON TABLE public.notifications_queue IS 'A queue for processing and sending email notifications asynchronously.';
COMMENT ON COLUMN public.notifications_queue.status IS 'The processing status of the notification job.';
COMMENT ON COLUMN public.notifications_queue.notification_params IS 'A JSONB object containing all parameters needed by the email template (e.g., amount, reason).';
